### PR TITLE
feat: ackermann drive2 plugin

### PR DESCRIPTION
**Pull request by afonsofonbraga**
# Initial discussions
There should always be at least a [Notion](https://www.notion.so/brisa-robotica/Tasks-f2007f6ea2154c22870d810b4a2660d1) task for a PR. Don't forget to fill information in the task: project, tasks, iteration (Sprint) etc.

- [x] [Notion](https://www.notion.so/brisa-robotica/610b5c0d9c7d450385609016ea62e399?v=9df65b4479a64d339d95559d4b22e3c7&p=4e9469a929584a6c9ae82676b9e49fdc&pm=s) Creating a Gazebo controller for Ackermann vehicles
- [ ] Conversation initiated in slack: [Slack conversation link]() 
- [ ] Github issue: 
- [ ] In person  

# Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

# What I did

When creating the urdf for the forklift Toyota 7fbh25 we needed an Ackermann controller for gazebo. The one presented by gazebo_ros_pkgs didn't work perfectly with the urdf model. Therefore, to speed up our production I developed a plugin based on the tricycle_controller_plugin that we already have.
# How I did it
I copied the gazebo_ros_tricycle_drive and created the gazebo_ros_ackermann_drive2.
# I am not sure about

# How I tested
Tested in simulation
# I'm not a dummy, so I've checked these

- [x] 📑 I documented correctly following our [guidelines](https://www.notion.so/brisa-robotica/Contributing-guidelines-48ad0483ea2c4975a71bee17b3f28a77#8291d74a46d14377bf307f17f9141ef7)
- [x] 💯 I tested locally and it is working
- [ ] ☝️ I increased the version following [Semantic versioning](https://semver.org/)
- [x] 🟢 My code does not fail neither code linting checks nor unit test.

Thank you! ❤️

### CODE REVIEW

**Comment by Minipada** [comment]
can we call it differently than ackermann2? It doesn't tell much of how different it is

**Comment by afonsofonbraga** [comment]
@Minipada yes, do you have any suggestions? It is an Ackermann plugin based on the tricycle plugin. should it be ackermann_from_tricycle?

**Review by GB255 — APPROVED** [review]

**Comment by Minipada** [comment]
@afonsofonbraga agree

**Comment by afonsofonbraga** [comment]
@Minipada All set

**Review by Minipada — APPROVED** [review]

**Pull request merged**
